FROM resin/%%RESIN_MACHINE_NAME%%-debian

ENV INITSYSTEM on

RUN apt-get -y update && \
apt-get -y install openssh-server && \
apt-get install -y network-manager && \
apt-get install -y apache2 && \
apt-get install -y php libapache2-mod-php php-mysql php-curl php-json php-cgi && \
sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
